repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        language_version: python3.7
