github:
  task-re: SM-\d+

  # Step 1. Fill Github auth token (check README.md)
  token: XXX


jira:
  connection:
    server: https://tangle.atlassian.net

    # Step 2. Fill JIRA credentials (check README.md)
    user: jira_login (email)
    token: XXX
  release-task:
    project: SM
    type: Release

    # Step 3. choose your component
    component: Frontend
    component: Native
    component: BSF
    component: BSM

    # can be omitted if default params are not changed
    name: '{component} release {version}'
    link-type: "parent of"

  # can be omitted if default params are not changed
  transition:
    # When release is finished move Release task from/to status
    release-from-status: "On Production"
    release-to-status: "Release Merged"

    # When release is finished move Release *child* tasks from/to status
    child-from-status: "To Deploy"
    child-to-status: "Done"

    # Auto finish Jira FixVersion
    # 1. filter to understand which tasks are finished
    child-final-statuses:
    - "Done"
    - "Closed"
    # 2. filter for tasks that are not managed by release-tool
    child-task-types-to-skip:
    - "Story"

hooks:
  # Step 4. Choose you hooks
  # for backend:
  get-version: python submodules/shared/src/deploy/scripts/release-utils.py get-version
  set-version: python submodules/shared/src/deploy/scripts/release-utils.py set-version {version}

  # for frontend:
  get-version: npm run --silent print-version
  set-version: yarn version --no-git-tag-version --new-version {version} && npm i


# can be omitted if default params are not changed
git:
  base: develop
  master: master
  release-name: release-{version}
