name: Link tasks to JIRA release

on:
  push:
    branches:
      - 'release-*'
  pull_request:
    branches:
      - 'release-*'

jobs:
  link-tasks-to-jira-release:
    name: Link tasks to JIRA release
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Download image
        run: docker pull statusmoney/release-tool
      -
        name: Make links
        run: ./release ci make-links
        env:
          RELEASE_TOOL_JIRA_TOKEN: ${{ secrets.RELEASE_TOOL_JIRA_TOKEN }}
          RELEASE_TOOL_GITHUB_TOKEN: ${{ secrets.RELEASE_TOOL_GITHUB_TOKEN }}
